### ISSUE TITLE
Resource info/meta

### ISSUE THREAD

**Issue by manyk** [wallstreetio/ontraport#1]
Resource.php:234-253

Ontraport API accepts condition parameter for getInfo namespace but Meta request should be empty.

I think "array $data = []" should be present as parameter for info() but not for meta()

**Comment by tamerashkar** [comment]
Hey @manyk 

According to http://api.ontraport.com/doc/#retrieve-object-meta, Ontraport allows you to pass a `format` field into the `meta` endpoint. For example:

```php
$ontraport->contacts->meta(['format' => 'byName']);
```

As for the parameters for the `info` endpoint, they can be used as such:

```php
$ontraport->contacts
    ->search('string')
    ->searchNotes()
    ->info();
```

In 154770c691ac5c8a8f67aecea70a8bd3d4ac9887, I have added the ability to pass those parameters through the `info` method as well.

```php
$ontraport->contacts->info(['search' => 'string', 'searchNotes' => true]);
```
